name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: [10.x]
      - name: npm ci, lint, build prod
        run: |
          npm ci
          npm run lint
          npm run pkg

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: [10.x]
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish ./dist/ngant --access public
        env:
            NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: [10.x]
          registry-url: https://npm.pkg.github.com/
          scope: '@tinyking'
      - run: npm ci
      - run: npm publish ./dist/ngant
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_NPM_TOKEN}}
